---
services:

  db:
    image: postgres:15
    container_name: bdd-zytho
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: api_beer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "2000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api-zytho
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db-data: